dist: xenial
language: python
cache: pip
sudo: false
python:
- pypy2.7-5.10.0
- pypy3.5-5.10.1
- '2.7'
- '3.8'
- '3.7'
- '3.6'
- '3.5'
- nightly
install:
- pip install --upgrade pip
- pip install flake8 pytest-cov .
- pip install -e '.[tests]'
script:
- flake8 --ignore=E999 methodtools.py tests setup.py
- pytest --cov=methodtools -vv tests/
after_success:
- bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
  - python: nightly
